spring.application.name=footballapp

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fan_tracker_db
spring.datasource.username=postgres
spring.datasource.password=zaq1@WSX

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Logowanie zapytan
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true